# This is a basic workflow to help you get started with Actions

name: Web-Front-Build-Test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-test:
    runs-on: ubuntu-20.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps: 
    - uses: actions/checkout@v3
    
    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Build-Test Start!
        
    - name: Setup node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
      
    - run : npm install
    # - run: npm ci
    - run: npm run build --if-present
    # - run: npm test
